= MOHPC
:toc:
:sectnums:

== Introduction

This library helps you to read Medal of Honor: Allied Assault (all versions) assets using C++. It has been well-tested on a big project https://moh-rises.com/[MOHUE] and is considered stable.

== Requirements

All::
- CMake 3.1 or higher

Windows::
- A compiler, like Visual Studio, thats support C++17

Unix::
- GCC 8.x or higher
- stdc++fs library on Unix

Third-party components will be downloaded and compiled automatically.

== Compatibility

This library can be built on Windows and Unix systems, for any architecture.

.Compatibility list
|===
| Platform | x86     | x64      | ARM
| Windows  | Best    | Best     | Best
| Linux    | Good    | Good     | Unknown 
| MAC      | Unknown | Unknown  | Unknown
|===

=== Legend

[horizontal]
Best:: Fully working with no encountered crashes or bugs.

Good:: Starts and load some assets, but was not tested enough.

Unknown:: Absence of testing, but this does not mean the library will not work.

=== TODO

This README will change over time.
