:source-highlighter: rouge
:rouge-style: pastie

= MOHPC
Author Ludovic
:toc:
:sectnums:

== Introduction

This library helps you to read Medal of Honor: Allied Assault (all versions) assets using C++. It's working fine on a big project (link:https://moh-rises.com/[MOHUE]) and is considered stable.

Some info about abbreviations:

[horizontal]
MOHAA:: Medal of Honor Allied Assault
MOHAAS:: Medal of Honor Allied Assault: Spearhead
MOHAAB:: Medal of Honor Allied Assault: Breakthrough

== Requirements

All::
- CMake 3.1 or higher

Windows::
- A compiler, like Visual Studio, that support C++17

Unix::
- GCC 8.x or higher (C++17 compiler)
- stdc++fs library on Unix

Third-party components should be downloaded and compiled automatically.
This library relies on STL as it's part of C++ standard.

== Compatibility

This library can be built on Windows and Unix systems, for any architecture.

.Compatibility list
|===
| Platform | x86     | x64      | ARM
| Windows  | Best    | Best     | Best
| Linux    | Good    | Good     | Unknown 
| Mac      | Unknown | Unknown  | Unknown
|===

[horizontal]
Best:: Fully working with no encountered crashes or bugs.

Good:: Starts and load some assets, but was not tested enough.

Unknown:: Absence of testing, but this does not mean the library will not work.

== Features

* Assets reader.
* Collision test.
* Model renderer.
* Networking / Player movement.

=== Supported assets

* BSP (map)
* DCL (decals)
* Models and animations
** SKB (model)
** SKD from all expansions (model)
** SKC from all expansions (animation)
** TIKI files / Emitters
* Images
** JPEG
** TGA
** DDS
* Sounds
* Shaders

=== Networking

* Connect to server.
** Supports AA 1.0-1.11 | SH 2.0-2.15 | BT 2.30-2.40.
* Query server list from master server.
* Query LAN server list.
* Query server status/info.
* Handlers for monitoring events.

==== Supported protocols versions

The client can connect to any server that is using one of the following protocols:

[horizontal]
5:: MOHAA Demo 0.05 (SP version).
6:: MOHAA 1.0.
8:: MOHAA 1.1.
15:: MOHAAS 2.0.
16:: MOHAAS 2.11 and MOHAAB demo 0.30.
17:: MOHAAS 2.11 / 2.15 | MOHAAB 2.30 / 2.40b.

Note: Breakthrough shares the same protocol as Spearhead, excepts it adds "Breakthrough" clientType value when connecting.

Note 2: Protocol version 5 is supported, but the SP demo was not compiled with remote network support.

==== In-game

* Download is supported.
* Entities/snapshots fetching.
* Full support for realtime packets/messages processing.
* Game events parsing, callbacks & notifications.
* Interpolation/Extrapolation support.
* Player movement prediction and local collision support.
* Radar support (requires the server to be running at least SH 2.0), used to keep track of teammates when the server doesn't send to the client (non-pvs).
* User input simulation.

== Example

The following example demonstrates how to load an asset and test collision:

[source,cpp]
----
#include <MOHPC/Managers/AssetManager.h>
#include <MOHPC/Managers/FileManager.h>
#include <MOHPC/Managers/ShaderManager.h>

int main(int argc, char *argv[])
{
    MOHPC::AssetManager AM;
    MOHPC::FileManager* FM = AM.GetFileManager();
    // setup the game directory
    // will load all pak files from Allied Assault, Spearhead and Breakthrough.
    FM->FillGameDirectory("D:\\Path\\To\\Mohaa");
    //FM->FillGameDirectory("/home/mohaa/") // the path to mohaa in unix systems

    // load a map (mohdm6)
    MOHPC::BSPPtr bspLevel = AM.LoadAsset<MOHPC::BSP>("/maps/dm/mohdm6.bsp");
    
    // setup collision
    MOHPC::CollisionWorldPtr cm = MOHPC::CollisionWorld::create();
    bspLevel->FillCollisionWorld(*cm);

    // trace through world
    MOHPC::Vector start(0, 0, 0);
    MOHPC::Vector end(0, 0, -500);
    cm.CM_BoxTrace(&results, start, end, MOHPC::Vector(), MOHPC::Vector(), 5, MOHPC::ContentFlags::MASK_PLAYERSOLID, true);

    // fraction should be less than 1 because of the terrain
}
----

=== TODO

This README will change over time.
